// <auto-generated />
using DrywallDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrywallDB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220531181847_changedHasPrecisionToHasColumnType")]
    partial class changedHasPrecisionToHasColumnType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DrywallModels.Models.Drywall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("Length")
                        .HasMaxLength(1000)
                        .HasColumnType("real");

                    b.Property<int>("WallTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WallTypeId");

                    b.ToTable("Drywalls");
                });

            modelBuilder.Entity("DrywallModels.Models.WallType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("FirstLayer")
                        .HasColumnType("int");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("SecondLayer")
                        .HasColumnType("int");

                    b.Property<decimal>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,3)")
                        .HasDefaultValue(0.05m);

                    b.HasKey("Id");

                    b.ToTable("WallTypes");
                });

            modelBuilder.Entity("DrywallModels.Models.Drywall", b =>
                {
                    b.HasOne("DrywallModels.Models.WallType", "WallType")
                        .WithMany("Drywalls")
                        .HasForeignKey("WallTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WallType");
                });

            modelBuilder.Entity("DrywallModels.Models.WallType", b =>
                {
                    b.Navigation("Drywalls");
                });
#pragma warning restore 612, 618
        }
    }
}
